# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

# Datas are feeded for development On 04/13/2014 for below tables
City.create([{ :city_name => 'Bangalore' }, { :city_name => 'Delhi' }, { :city_name => 'Faridabad' }, { :city_name => 'Ghaziabad' }, { :city_name => 'Gurgaon' }, { :city_name => 'Noida' }])

Service.create([{:service_type => 'Food Sharing'}])
Service.create([{:service_type => 'Book Sharing'}])
Service.create([{:service_type => 'Skill Sharing'}])

FoodType.create([{:name => 'Vegetarian'}, {:name => 'Non-Vegetarian'},{:name => 'Any'}])

MealType.create([{:name => 'Breakfast'}, {:name => 'Lunch'}, {:name => 'Dinner'}, {:name => 'Any'}])

SubCategory.create([
{ :sub_category_type => 'All' },
{ :sub_category_type => 'Dance & Fitness' }, 
{ :sub_category_type => 'Music' }, 
{ :sub_category_type => 'Cooking' }, 
{ :sub_category_type => 'Teaching & Education' }, 
{ :sub_category_type => 'Professional Skill' }, 
{ :sub_category_type => 'Sports' }, 
{ :sub_category_type => 'Art and Crafts'}])

Region.create([
{ :name => 'North Indian' }, 
{ :name => 'Punjabi Food' }, 
{ :name => 'South Indian' }, 
{ :name => 'Bengali' }, 
{ :name => 'Konkani Food' }, 
{ :name => 'Goan' }, 
{ :name => 'Malwani' }, 
{ :name => 'Rajasthani' }, 
{ :name => 'Northeast India' }, 
{ :name => 'Hyderabadi' }, 
{ :name => 'Italian' }, 
{ :name => 'Thai' }, 
{ :name => 'Chinese' }, 
{ :name => 'Mexican' }, 
{ :name => 'Continental' }, 
{ :name => 'Any'}])


Provider.create([{ :provider_type => 'Individual Food Provider' }, { :provider_type => 'Caterers'},{ :provider_type => 'Chefs'}])


Location.create([{ :location_name => 'Adugodi', :city_id => 1}, 
{:location_name => 'Agaram', :city_id => 1}, 
{:location_name => 'Arabic College', :city_id => 1}, 
{:location_name => 'Arakere Gate', :city_id => 1}, 
{:location_name => 'Ashok Nagar', :city_id => 1},
{:location_name => 'Austin Town', :city_id => 1}, 
{:location_name => 'Balaji Nagar', :city_id => 1},
{:location_name => 'Banashankari', :city_id => 1}, 
{:location_name => 'Banaswadi', :city_id => 1}, 
{:location_name => 'Bangalore CBD', :city_id => 1}, 
{:location_name => 'Bangalore University', :city_id => 1}, 
{:location_name => 'Bannerghatta Road', :city_id => 1}, 
{:location_name => 'Basavangudi', :city_id => 1}, 
{:location_name => 'Basaveshwara Nagar', :city_id => 1}, 
{:location_name => 'Bellandur', :city_id => 1}, 
{:location_name => 'Benson Town', :city_id => 1}, 
{:location_name => 'Bhoopasandra', :city_id => 1}, 
{:location_name => 'Bidadi', :city_id => 1}, 
{:location_name => 'Bilekahalli', :city_id => 1}, 
{:location_name => 'Bommanahalli', :city_id => 1}, 
{:location_name => 'Brigade Road', :city_id => 1}, 
{:location_name => 'Brookefield', :city_id => 1}, 
{:location_name => 'BTM Layout', :city_id => 1}, 
{:location_name => 'BVK Iyengar Road', :city_id => 1}, 
{:location_name => 'Byatarayanapura', :city_id => 1}, 
{:location_name => 'C V Raman Nagar', :city_id => 1}, 
{:location_name => 'Carmelaram', :city_id => 1}, 
{:location_name => 'Chamarajpet', :city_id => 1}, 
{:location_name => 'Chandra Layout', :city_id => 1}, 
{:location_name => 'Chickpete', :city_id => 1}, 
{:location_name => 'Chikkabanavara', :city_id => 1}, 
{:location_name => 'Church Street', :city_id => 1}, 
{:location_name => 'Commercial Street', :city_id => 1}, 
{:location_name => 'Cooke Town', :city_id => 1}, 
{:location_name => 'Cox Town', :city_id => 1}, 
{:location_name => 'Crescent Road', :city_id => 1},
{:location_name => 'Cubbon Park', :city_id => 1}, 
{:location_name => 'Cunningham Road', :city_id => 1},
{:location_name => 'D J Halli', :city_id => 1},
{:location_name => 'Dasarahalli', :city_id => 1},
{:location_name => 'Devanahalli', :city_id => 1},
{:location_name => 'Dickenson Road', :city_id => 1},
{:location_name => 'Dispensary Road', :city_id => 1},
{:location_name => 'Doddaballapur Main Road', :city_id => 1},
{:location_name => 'Doddanekundi', :city_id => 1},
{:location_name => 'Dollars Colony', :city_id => 1},
{:location_name => 'Domlur', :city_id => 1},
{:location_name => 'Double Road', :city_id => 1},
{:location_name => 'Ejipura', :city_id => 1},
{:location_name => 'Electronic City', :city_id => 1},
{:location_name => 'Frazer Town', :city_id => 1},
{:location_name => 'Gandhi Nagar', :city_id => 1},
{:location_name => 'Ganga Nagar', :city_id => 1},
{:location_name => 'Gavipuram', :city_id => 1},
{:location_name => 'HAL 2nd Stage', :city_id => 1},
{:location_name => 'HAL 3rd Stage', :city_id => 1},
{:location_name => 'HAL Airport Road', :city_id => 1},
{:location_name => 'Halasuru', :city_id => 1},
{:location_name => 'Hanumantha Nagar', :city_id => 1},
{:location_name => 'Haralur Road', :city_id => 1},
{:location_name => 'Haudin Road', :city_id => 1},
{:location_name => 'HBR Layout', :city_id => 1},
{:location_name => 'Hebbal', :city_id => 1},
{:location_name => 'Hennur', :city_id => 1},
{:location_name => 'Hesaraghatta Road', :city_id => 1},
{:location_name => 'Hoskote', :city_id => 1},
{:location_name => 'Hosur Road', :city_id => 1},
{:location_name => 'HRBR Layout', :city_id => 1},
{:location_name => 'HSR Layout', :city_id => 1},
{:location_name => 'Indira Nagar', :city_id => 1},
{:location_name => 'Infantry Road', :city_id => 1},
{:location_name => 'J C Nagar', :city_id => 1},
{:location_name => 'J P Nagar', :city_id => 1},
{:location_name => 'Jakkur', :city_id => 1},
{:location_name => 'Jalahalli', :city_id => 1},
{:location_name => 'Jayamahal', :city_id => 1},
{:location_name => 'Jayanagar', :city_id => 1},
{:location_name => 'JC Road', :city_id => 1},
{:location_name => 'Jeevan Bima Nagar', :city_id => 1},
{:location_name => 'Jnana Bharathi', :city_id => 1},
{:location_name => 'K G Nagar', :city_id => 1},
{:location_name => 'Kadubeesanahalli', :city_id => 1},
{:location_name => 'Kadugodi', :city_id => 1},
{:location_name => 'Kaggalipura', :city_id => 1},
{:location_name => 'Kalasipalayam', :city_id => 1},
{:location_name => 'Kalyan Nagar', :city_id => 1},
{:location_name => 'Kamakshipalya', :city_id => 1},
{:location_name => 'Kammanahalli', :city_id => 1},
{:location_name => 'Kanakapura Main Road', :city_id => 1},
{:location_name => 'Kanakapura Road', :city_id => 1},
{:location_name => 'Kasturba Road', :city_id => 1},
{:location_name => 'Kasturi Nagar', :city_id => 1},
{:location_name => 'Kathriguppe', :city_id => 1},
{:location_name => 'Kempegowda', :city_id => 1},
{:location_name => 'Kengeri', :city_id => 1},
{:location_name => 'KG Road', :city_id => 1},
{:location_name => 'KH Road', :city_id => 1},
{:location_name => 'Kodihalli', :city_id => 1},
{:location_name => 'Konanakunte', :city_id => 1},
{:location_name => 'Koramangala', :city_id => 1},
{:location_name => 'Kothanur', :city_id => 1},
{:location_name => 'KR Market', :city_id => 1},
{:location_name => 'KR Road', :city_id => 1},
{:location_name => 'Krishnarajapura', :city_id => 1},
{:location_name => 'Kumara Krupa Road', :city_id => 1},
{:location_name => 'Kumara Park East', :city_id => 1},  
{:location_name => 'Kumara Park West', :city_id => 1},
{:location_name => 'Kumaraswamy Layout', :city_id => 1},
{:location_name => 'Kumbalgodu', :city_id => 1},
{:location_name => 'Laggere', :city_id => 1},
{:location_name => 'Langford Gardens', :city_id => 1},
{:location_name => 'Langford Road', :city_id => 1},
{:location_name => 'Lavelle Road', :city_id => 1},
{:location_name => 'Lingarajapuram', :city_id => 1},
{:location_name => 'Madivala', :city_id => 1},
{:location_name => 'Magrath Road', :city_id => 1},
{:location_name => 'Mahadevapura', :city_id => 1},
{:location_name => 'Mahalakshmi Layout', :city_id => 1},
{:location_name => 'Main Guard Cross Road', :city_id => 1},
{:location_name => 'Malleswaram', :city_id => 1},
{:location_name => 'Marathahalli', :city_id => 1},
{:location_name => 'Maruthi Sevanagar', :city_id => 1},
{:location_name => 'Mathikere', :city_id => 1},
{:location_name => 'MG Road', :city_id => 1},
{:location_name => 'Millers Road', :city_id => 1},
{:location_name => 'Mission Road', :city_id => 1},
{:location_name => 'Murugeshpalya', :city_id => 1},
{:location_name => 'Museum Road', :city_id => 1},
{:location_name => 'Mysore Road', :city_id => 1},
{:location_name => 'Nagarbhavi', :city_id => 1},
{:location_name => 'Nagasandra', :city_id => 1},
{:location_name => 'Nagashettyhalli', :city_id => 1},
{:location_name => 'Nagawara', :city_id => 1},
{:location_name => 'Nandidurga Road Crescent', :city_id => 1},
{:location_name => 'Nayandahalli', :city_id => 1},
{:location_name => 'New BEL Road', :city_id => 1},
{:location_name => 'New Thippasandra', :city_id => 1},
{:location_name => 'Old Airport Road', :city_id => 1},
{:location_name => 'Old Madras Road', :city_id => 1},
{:location_name => 'Old Race Course Road', :city_id => 1},
{:location_name => 'Padmanabha Nagar', :city_id => 1},
{:location_name => 'Palace Cross Road', :city_id => 1},
{:location_name => 'Palace Guttahalli', :city_id => 1},
{:location_name => 'Peenya Industrial Area', :city_id => 1},
{:location_name => 'Puttenahalli', :city_id => 1},
{:location_name => 'Queens Road', :city_id => 1},
{:location_name => 'Rajajinagar', :city_id => 1},
{:location_name => 'Rajanukunte', :city_id => 1},
{:location_name => 'Rajkunte', :city_id => 1},
{:location_name => 'Ramanagaram', :city_id => 1},
{:location_name => 'Residency Road', :city_id => 1},
{:location_name => 'Richmond Road', :city_id => 1},
{:location_name => 'Richmond Town', :city_id => 1},
{:location_name => 'RMV 2nd Stage', :city_id => 1},
{:location_name => 'RR Nagar', :city_id => 1},
{:location_name => 'RT Nagar', :city_id => 1},
{:location_name => 'Sadahalli', :city_id => 1},
{:location_name => 'Sadashiv Nagar', :city_id => 1},
{:location_name => 'Sahakara Nagar', :city_id => 1},
{:location_name => 'Sanjaynagar', :city_id => 1},
{:location_name => 'Sanjeevini Nagar', :city_id => 1},
{:location_name => 'Sankey Road', :city_id => 1},
{:location_name => 'Sarjapur', :city_id => 1},
{:location_name => 'Seshadripuram', :city_id => 1},
{:location_name => 'Shampura', :city_id => 1},
{:location_name => 'Shanthinagar', :city_id => 1},
{:location_name => 'Shivaji Nagar', :city_id => 1},
{:location_name => 'Srirampuram', :city_id => 1},
{:location_name => 'St Thomas Town', :city_id => 1},
{:location_name => 'St. Johns Road', :city_id => 1},
{:location_name => 'St.Marks Road', :city_id => 1},
{:location_name => 'Subramanyapura', :city_id => 1},
{:location_name => 'Sultanpalya', :city_id => 1},
{:location_name => 'Tannery Road', :city_id => 1},
{:location_name => 'Thyagaraja Nagar', :city_id => 1},
{:location_name => 'Tumkur Road', :city_id => 1},
{:location_name => 'Varthur Road', :city_id => 1},
{:location_name => 'vasanth nagar', :city_id => 1},
{:location_name => 'Victoria Road', :city_id => 1},
{:location_name => 'Vidyaranyapura', :city_id => 1},
{:location_name => 'Vijayanagar', :city_id => 1},
{:location_name => 'Vimanapura', :city_id => 1},
{:location_name => 'Virgonagar', :city_id => 1},
{:location_name => 'Viswaneedam', :city_id => 1},
{:location_name => 'Vittal Mallya Road', :city_id => 1},
{:location_name => 'Vivek Nagar', :city_id => 1},
{:location_name => 'VV Puram', :city_id => 1},
{:location_name => 'Vyalikaval', :city_id => 1},
{:location_name => 'Walton Road', :city_id => 1},
{:location_name => 'Wheelers Road', :city_id => 1},
{:location_name => 'Whitefield', :city_id => 1},
{:location_name => 'Wilson Garden', :city_id => 1},
{:location_name => 'Yelahanka', :city_id => 1},
{:location_name => 'Yeshwanthpura', :city_id => 1},

{:location_name => 'Adarsh Nagar', :city_id => 2},
{:location_name => 'Adhchini Village', :city_id => 2},
{:location_name => 'Ajmeri Gate', :city_id => 2},
{:location_name => 'Alaknanda', :city_id => 2},
{:location_name => 'Ali Pur', :city_id => 2},
{:location_name => 'Ambedkar Nagar', :city_id => 2},
{:location_name => 'Ambedkar Road', :city_id => 2},
{:location_name => 'Anand Niketan', :city_id => 2},
{:location_name => 'Anand Parbat', :city_id => 2},
{:location_name => 'Anand Parbat Industrial Area', :city_id => 2},
{:location_name => 'Anand Vihar', :city_id => 2},
{:location_name => 'Andrews Ganj', :city_id => 2},
{:location_name => 'Arjun Nagar', :city_id => 2},
{:location_name => 'Arya Nagar', :city_id => 2},
{:location_name => 'Asaf Ali Road', :city_id => 2},
{:location_name => 'Ashok Nagar', :city_id => 2},
{:location_name => 'Ashok Vihar Phase 1', :city_id => 2},
{:location_name => 'Ashok Vihar Phase 2', :city_id => 2},
{:location_name => 'Ashok Vihar Phase 3', :city_id => 2},
{:location_name => 'Ashram', :city_id => 2},
{:location_name => 'Aurangzeb Road', :city_id => 2},
{:location_name => 'Aurobindo Marg', :city_id => 2},
{:location_name => 'Azad Market', :city_id => 2},
{:location_name => 'Azad Nagar', :city_id => 2},
{:location_name => 'Azad Nagar East', :city_id => 2},
{:location_name => 'Azadpur', :city_id => 2},
{:location_name => 'Babarpur', :city_id => 2},
{:location_name => 'Badarpur', :city_id => 2},
{:location_name => 'Badarpur Border', :city_id => 2},
{:location_name => 'Badli', :city_id => 2},
{:location_name => 'Badli Industrial Area', :city_id => 2},
{:location_name => 'Bahadur Shah Zafar Marg', :city_id => 2},
{:location_name => 'Bahadurgarh', :city_id => 2},
{:location_name => 'Bali Nagar', :city_id => 2},
{:location_name => 'Baljit Nagar', :city_id => 2},
{:location_name => 'Bara Hindu Rao', :city_id => 2},
{:location_name => 'Barakhamba Road', :city_id => 2},
{:location_name => 'Basai Darapur', :city_id => 2},
{:location_name => 'Bawana', :city_id => 2},
{:location_name => 'Ber Sarai', :city_id => 2},
{:location_name => 'Bhagirath Palace', :city_id => 2},
{:location_name => 'Bhagirathi Vihar', :city_id => 2},
{:location_name => 'Bhagwan Nagar', :city_id => 2},
{:location_name => 'Bhajan Pura', :city_id => 2},
{:location_name => 'Bharat Nagar', :city_id => 2},
{:location_name => 'Bhikaji Cama Place', :city_id => 2},
{:location_name => 'Bhim Nagar', :city_id => 2},
{:location_name => 'Bhogal', :city_id => 2},
{:location_name => 'Bhola Nath Nagar', :city_id => 2},
{:location_name => 'Bijwasan', :city_id => 2},
{:location_name => 'Brahmapuri', :city_id => 2},
{:location_name => 'Brahmpuri Road', :city_id => 2},
{:location_name => 'Brij Vihar', :city_id => 2},
{:location_name => 'Budh Nagar', :city_id => 2},
{:location_name => 'Budh Vihar', :city_id => 2},
{:location_name => 'Burari', :city_id => 2},
{:location_name => 'Chanakya Place', :city_id => 2},
{:location_name => 'Chander Nagar, Janakpuri', :city_id => 2},
{:location_name => 'Chandni Chowk', :city_id => 2},
{:location_name => 'Chandu Nagar', :city_id => 2},
{:location_name => 'Chankyapuri', :city_id => 2},
{:location_name => 'Chattarpur', :city_id => 2},
{:location_name => 'Chawri Bazar', :city_id => 2},
{:location_name => 'Chhatarpur', :city_id => 2},
{:location_name => 'Chirag Delhi', :city_id => 2},
{:location_name => 'Chiranjeev Vihar', :city_id => 2},
{:location_name => 'Chittaranjan Park', :city_id => 2},
{:location_name => 'Civil Lines, New Delhi', :city_id => 2},
{:location_name => 'Connaught Circus', :city_id => 2},
{:location_name => 'Connaught Place', :city_id => 2},
{:location_name => 'Dabri', :city_id => 2},
{:location_name => 'Dadri Road', :city_id => 2},
{:location_name => 'Dakshinpuri', :city_id => 2},
{:location_name => 'Dallupura', :city_id => 2},
{:location_name => 'Dariba Kalan', :city_id => 2},
{:location_name => 'Daryaganj', :city_id => 2},
{:location_name => 'Daya Basti', :city_id => 2},
{:location_name => 'Dayalpur', :city_id => 2},
{:location_name => 'Dayanand Colony', :city_id => 2},
{:location_name => 'Dayanand Vihar', :city_id => 2},
{:location_name => 'DDA Flats Kalkaji', :city_id => 2},
{:location_name => 'Defence Colony', :city_id => 2},
{:location_name => 'Delhi Cantonment', :city_id => 2},
{:location_name => 'Delhi Gate', :city_id => 2},
{:location_name => 'Delhi High Court', :city_id => 2},
{:location_name => 'Derawal Nagar', :city_id => 2},
{:location_name => 'Desh Bandhu Gupta Road', :city_id => 2},
{:location_name => 'Dev Nagar', :city_id => 2},
{:location_name => 'Dhaula Kuan', :city_id => 2},
{:location_name => 'Dilshad Colony', :city_id => 2},
{:location_name => 'Dilshad Garden', :city_id => 2},
{:location_name => 'Dr. Mukherjee Nagar', :city_id => 2},
{:location_name => 'Durgapuri', :city_id => 2},
{:location_name => 'Dwarka Sector 10', :city_id => 2},
{:location_name => 'Dwarka Sector 11', :city_id => 2},
{:location_name => 'Dwarka Sector 12', :city_id => 2},
{:location_name => 'Dwarka Sector 19', :city_id => 2},
{:location_name => 'Dwarka Sector 5', :city_id => 2},
{:location_name => 'Dwarka Sector 6', :city_id => 2},
{:location_name => 'Dwarka Sector 6', :city_id => 2},
{:location_name => 'Dwarka Sector 7', :city_id => 2},
{:location_name => 'Dwarka Sector 9', :city_id => 2},
{:location_name => 'Dwarka Sector 3', :city_id => 2},
{:location_name => 'Dwarka Sector 4', :city_id => 2},
{:location_name => 'East Krishna Nagar', :city_id => 2},
{:location_name => 'East Of Kailash', :city_id => 2},
{:location_name => 'East Patel Nagar', :city_id => 2},
{:location_name => 'East Vinod Nagar', :city_id => 2},
{:location_name => 'Fateh Nagar', :city_id => 2},
{:location_name => 'Fatehpuri', :city_id => 2},
{:location_name => 'Friends Colony', :city_id => 2},
{:location_name => 'Friends Colony East', :city_id => 2},
{:location_name => 'Gagan Vihar', :city_id => 2},
{:location_name => 'Gandhi Nagar', :city_id => 2},
{:location_name => 'Ganesh Nagar', :city_id => 2},
{:location_name => 'Garhi', :city_id => 2},
{:location_name => 'Gautam Nagar', :city_id => 2},
{:location_name => 'Gazipur', :city_id => 2},
{:location_name => 'GB Road', :city_id => 2},
{:location_name => 'Geeta Colony', :city_id => 2},
{:location_name => 'Geetanjali Enclave', :city_id => 2},
{:location_name => 'Gharoli', :city_id => 2},
{:location_name => 'Ghazipur', :city_id => 2},
{:location_name => 'Ghazipur Road', :city_id => 2},
{:location_name => 'Ghitorni', :city_id => 2},
{:location_name => 'Ghonda Chowk', :city_id => 2},
{:location_name => 'Gokalpuri', :city_id => 2},
{:location_name => 'Gole Market', :city_id => 2},
{:location_name => 'Golf Links', :city_id => 2},
{:location_name => 'Govindpuri Main', :city_id => 2},
{:location_name => 'GPO, Gole Dak Khana', :city_id => 2},
{:location_name => 'Greater Kailash', :city_id => 2},
{:location_name => 'Greater Kailash Enclave', :city_id => 2},
{:location_name => 'Greater Kailash Enclave I', :city_id => 2},
{:location_name => 'Greater Kailash I', :city_id => 2},
{:location_name => 'Greater Kailash II', :city_id => 2},
{:location_name => 'Greater Noida', :city_id => 2},
{:location_name => 'Green Park', :city_id => 2},
{:location_name => 'Green Park Extension', :city_id => 2},
{:location_name => 'Greenfield Colony', :city_id => 2},
{:location_name => 'GT Karnal Road', :city_id => 2},
{:location_name => 'GT Karnal Road', :city_id => 2},
{:location_name => 'GT Karnal Road Industrial Area', :city_id => 2},
{:location_name => 'GT Road', :city_id => 2},
{:location_name => 'Gulabi Bagh', :city_id => 2},
{:location_name => 'Gulmohar Park', :city_id => 2},
{:location_name => 'Guru Nanak Pura', :city_id => 2},
{:location_name => 'Guru Teg Bahadur Nagar', :city_id => 2},
{:location_name => 'Gurudwara Road', :city_id => 2},
{:location_name => 'Haidarpur', :city_id => 2},
{:location_name => 'Hamilton Road', :city_id => 2},
{:location_name => 'Hargovind Enclave', :city_id => 2},
{:location_name => 'Hari Nagar', :city_id => 2},
{:location_name => 'Hauz Khas', :city_id => 2},
{:location_name => 'Hauz Khas Enclave', :city_id => 2},
{:location_name => 'Hauz Khas Village', :city_id => 2},
{:location_name => 'Hauz Qazi', :city_id => 2},
{:location_name => 'IGI Airport', :city_id => 2},
{:location_name => 'INA Colony', :city_id => 2},
{:location_name => 'INA Market', :city_id => 2},
{:location_name => 'Inder Lok', :city_id => 2},
{:location_name => 'Inder Puri', :city_id => 2},
{:location_name => 'Indraprastha Extension', :city_id => 2},
{:location_name => 'Industrial Area, Mangolpuri, Phase 1', :city_id => 2},
{:location_name => 'IP Estate', :city_id => 2},
{:location_name => 'ITO', :city_id => 2},
{:location_name => 'Jacombpura', :city_id => 2},
{:location_name => 'Jaffrabad', :city_id => 2},
{:location_name => 'Jagatpuri', :city_id => 2},
{:location_name => 'Jahangir Puri', :city_id => 2},
{:location_name => 'Jahangirpuri', :city_id => 2},
{:location_name => 'Jail Road', :city_id => 2},
{:location_name => 'Jama Masjid', :city_id => 2},
{:location_name => 'Jamia Nagar', :city_id => 2},
{:location_name => 'Janakpuri', :city_id => 2},
{:location_name => 'Janakpuri District Centre', :city_id => 2},
{:location_name => 'Jangpura', :city_id => 2},
{:location_name => 'Jangpura Extension', :city_id => 2},
{:location_name => 'Janpath', :city_id => 2},
{:location_name => 'Jasola', :city_id => 2},
{:location_name => 'Jasola Vihar', :city_id => 2},
{:location_name => 'Jawahar Nagar', :city_id => 2},
{:location_name => 'Jhandewalan', :city_id => 2},
{:location_name => 'Jhandewalan Extension', :city_id => 2},
{:location_name => 'Jheel', :city_id => 2},
{:location_name => 'Jheel Khurenja', :city_id => 2},
{:location_name => 'Jhilmil Colony', :city_id => 2},
{:location_name => 'Jhilmil Industrial Area', :city_id => 2},
{:location_name => 'Jia Sarai', :city_id => 2},
{:location_name => 'Jitar Nagar', :city_id => 2},
{:location_name => 'Jor Bagh', :city_id => 2},
{:location_name => 'Kailash Colony', :city_id => 2},
{:location_name => 'Kailash Nagar', :city_id => 2},
{:location_name => 'Kalkaji', :city_id => 2},
{:location_name => 'Kalkaji Extension', :city_id => 2},
{:location_name => 'Kalu Sarai', :city_id => 2},
{:location_name => 'Kalyanpuri', :city_id => 2},
{:location_name => 'Kamla Nagar', :city_id => 2},
{:location_name => 'Kanti Nagar', :city_id => 2},
{:location_name => 'Kapashera', :city_id => 2},
{:location_name => 'Karampura', :city_id => 2},
{:location_name => 'Karampura West', :city_id => 2},
{:location_name => 'Karawal Nagar', :city_id => 2},
{:location_name => 'Karkar Duma', :city_id => 2},
{:location_name => 'Karol Bagh', :city_id => 2},
{:location_name => 'Kashmiri Gate', :city_id => 2},
{:location_name => 'Kasturba Gandhi Marg', :city_id => 2},
{:location_name => 'Katwaria Sarai', :city_id => 2},
{:location_name => 'Keshav Puram', :city_id => 2},
{:location_name => 'Khajuri Khas', :city_id => 2},
{:location_name => 'Khan Market', :city_id => 2},
{:location_name => 'Khanpur', :city_id => 2},
{:location_name => 'Khari Baoli', :city_id => 2},
{:location_name => 'Khichripur', :city_id => 2},
{:location_name => 'Khirki Extention', :city_id => 2},
{:location_name => 'Khureji Khas', :city_id => 2},
{:location_name => 'Khyala', :city_id => 2},
{:location_name => 'Kidwai Nagar', :city_id => 2},
{:location_name => 'Kilokri', :city_id => 2},
{:location_name => 'Kingsway Camp', :city_id => 2},
{:location_name => 'Kirti Nagar', :city_id => 2},
{:location_name => 'Kirti Nagar Industrial Area', :city_id => 2},
{:location_name => 'Kishan Ganj', :city_id => 2},
{:location_name => 'Kishangarh', :city_id => 2},
{:location_name => 'Kondli', :city_id => 2},
{:location_name => 'Kotla', :city_id => 2},
{:location_name => 'Kotla Mubarakpur', :city_id => 2},
{:location_name => 'Krishna Nagar', :city_id => 2},
{:location_name => 'Krishna Nagar East', :city_id => 2},
{:location_name => 'Krishna Park', :city_id => 2},
{:location_name => 'Lado Sarai', :city_id => 2},
{:location_name => 'Lajpat Nagar I', :city_id => 2},
{:location_name => 'Lajpat Nagar II', :city_id => 2},
{:location_name => 'Lajpat Nagar III', :city_id => 2},
{:location_name => 'Lajpat Nagar IV', :city_id => 2},
{:location_name => 'Lajpat Rai Market', :city_id => 2},
{:location_name => 'Lajwanti Garden', :city_id => 2},
{:location_name => 'Lawrence Road', :city_id => 2},
{:location_name => 'Laxmi Nagar', :city_id => 2},
{:location_name => 'Libaspur', :city_id => 2},
{:location_name => 'Lodhi Colony', :city_id => 2},
{:location_name => 'Lodhi estate', :city_id => 2},
{:location_name => 'Lodhi Road', :city_id => 2},
{:location_name => 'Lohia Nagar', :city_id => 2},
{:location_name => 'Loni Bhopura Road', :city_id => 2},
{:location_name => 'Loni Road', :city_id => 2},
{:location_name => 'Madangir', :city_id => 2},
{:location_name => 'Madanpur Khadar', :city_id => 2},
{:location_name => 'Madhu Vihar', :city_id => 2},
{:location_name => 'Madipur', :city_id => 2},
{:location_name => 'Maharani Bagh', :city_id => 2},
{:location_name => 'Mahavir Enclave', :city_id => 2},
{:location_name => 'Mahipalpur', :city_id => 2},
{:location_name => 'Mahipalpur Extension', :city_id => 2},
{:location_name => 'Malka Ganj', :city_id => 2},
{:location_name => 'Malviya Nagar', :city_id => 2},
{:location_name => 'Mandawali', :city_id => 2},
{:location_name => 'Mangolpur Kalan', :city_id => 2},
{:location_name => 'Mangolpuri', :city_id => 2},
{:location_name => 'Mangolpuri Industrial Area Phase 2', :city_id => 2},
{:location_name => 'Mansarovar Garden', :city_id => 2},
{:location_name => 'market near Laxmi Nagar', :city_id => 2},
{:location_name => 'Masjid Moth', :city_id => 2},
{:location_name => 'Masudpur', :city_id => 2},
{:location_name => 'Mathura Road', :city_id => 2},
{:location_name => 'Maujpur', :city_id => 2},
{:location_name => 'Mayapuri', :city_id => 2},
{:location_name => 'Mayapuri Industrial Area I', :city_id => 2},
{:location_name => 'Mayapuri Industrial Area II', :city_id => 2},
{:location_name => 'Mayur Vihar', :city_id => 2},
{:location_name => 'Mayur Vihar Phase 1', :city_id => 2},
{:location_name => 'Mayur Vihar Phase 2', :city_id => 2},
{:location_name => 'Mayur Vihar Phase 3', :city_id => 2},
{:location_name => 'Meera Bagh', :city_id => 2},
{:location_name => 'Meerut Road', :city_id => 2},
{:location_name => 'Meerut Road Industrial Area', :city_id => 2},
{:location_name => 'Mehrauli', :city_id => 2},
{:location_name => 'Mehrauli Road', :city_id => 2},
{:location_name => 'Minto Road', :city_id => 2},
{:location_name => 'Model Basti', :city_id => 2},
{:location_name => 'Model Town', :city_id => 2},
{:location_name => 'Model Town II', :city_id => 2},
{:location_name => 'Model Town III', :city_id => 2},
{:location_name => 'Mohammad Pur', :city_id => 2},
{:location_name => 'Mohammad Pur Majri', :city_id => 2},
{:location_name => 'Mohammadpur', :city_id => 2},
{:location_name => 'Mohan Co-Operative Industrial Estate', :city_id => 2},
{:location_name => 'Mohan Garden', :city_id => 2},
{:location_name => 'Molarband Extension', :city_id => 2},
{:location_name => 'Mori Gate', :city_id => 2},
{:location_name => 'Moti Bagh', :city_id => 2},
{:location_name => 'Moti Bagh South', :city_id => 2},
{:location_name => 'Moti Nagar', :city_id => 2},
{:location_name => 'Motia Khan', :city_id => 2},
{:location_name => 'Mujesar', :city_id => 2},
{:location_name => 'Mukarji West', :city_id => 2},
{:location_name => 'Mukherjee Nagar', :city_id => 2},
{:location_name => 'Mundka', :city_id => 2},
{:location_name => 'Munirka', :city_id => 2},
{:location_name => 'Nabi Karim', :city_id => 2},
{:location_name => 'Nai Sarak', :city_id => 2},
{:location_name => 'Najafgarh', :city_id => 2},
{:location_name => 'Najafgarh Road', :city_id => 2},
{:location_name => 'Najafgarh Road Industrial Area', :city_id => 2},
{:location_name => 'Nanakpura', :city_id => 2},
{:location_name => 'Nand Nagari', :city_id => 2},
{:location_name => 'Nangal Raya', :city_id => 2},
{:location_name => 'Nangloi', :city_id => 2},
{:location_name => 'Nangloi Extension', :city_id => 2},
{:location_name => 'Nangloi Jat', :city_id => 2},
{:location_name => 'Naraina', :city_id => 2},
{:location_name => 'Naraina Industrial Area', :city_id => 2},
{:location_name => 'Naraina Industrial Area Phase 1', :city_id => 2},
{:location_name => 'Naraina Vihar', :city_id => 2},
{:location_name => 'Narayana Industrial Area Phase 2', :city_id => 2},
{:location_name => 'Narela', :city_id => 2},
{:location_name => 'Narela Industrial Area', :city_id => 2},
{:location_name => 'Nathupura', :city_id => 2},
{:location_name => 'Naveen Shahdara', :city_id => 2},
{:location_name => 'Navyug, Market Lane', :city_id => 2},
{:location_name => 'Naya Bazar', :city_id => 2},
{:location_name => 'Neb Sarai', :city_id => 2},
{:location_name => 'Nehru Enclave', :city_id => 2},
{:location_name => 'Nehru Nagar', :city_id => 2},
{:location_name => 'Nehru Place', :city_id => 2},
{:location_name => 'Nehru Vihar', :city_id => 2},
{:location_name => 'Netaji Nagar', :city_id => 2},
{:location_name => 'Netaji Subhash Place', :city_id => 2},
{:location_name => 'New Friends Colony', :city_id => 2},
{:location_name => 'New Kondli', :city_id => 2},
{:location_name => 'New Lajpat Rai Market', :city_id => 2},
{:location_name => 'New Moti Nagar', :city_id => 2},
{:location_name => 'New Rajdhani Enclave', :city_id => 2},
{:location_name => 'New Rajendra Nagar', :city_id => 2},
{:location_name => 'New Rohtak Road', :city_id => 2},
{:location_name => 'Nirman Vihar', :city_id => 2},
{:location_name => 'Niti Bagh', :city_id => 2},
{:location_name => 'Nizamuddin East', :city_id => 2},
{:location_name => 'Nizamuddin West', :city_id => 2},
{:location_name => 'Noida Link Road', :city_id => 2},
{:location_name => 'Okhla', :city_id => 2},
{:location_name => 'Okhla Industrial Area Phase III', :city_id => 2},
{:location_name => 'Okhla Industrial Area Phase-1', :city_id => 2},
{:location_name => 'Okhla Industrial Area, Phase II Okhla', :city_id => 2},
{:location_name => 'Okhla Industrial Estate', :city_id => 2},
{:location_name => 'Old Rajendra Nagar', :city_id => 2},
{:location_name => 'Paharganj', :city_id => 2},
{:location_name => 'Palam', :city_id => 2},
{:location_name => 'Palam Colony', :city_id => 2},
{:location_name => 'Palam Village', :city_id => 2},
{:location_name => 'Palika Bazar', :city_id => 2},
{:location_name => 'Panchkuian Road', :city_id => 2},
{:location_name => 'Panchsheel Enclave', :city_id => 2},
{:location_name => 'Panchsheel Park', :city_id => 2},
{:location_name => 'Pandav Nagar', :city_id => 2},
{:location_name => 'Pankha Road', :city_id => 2},
{:location_name => 'Parliament Street', :city_id => 2},
{:location_name => 'Parwana Road', :city_id => 2},
{:location_name => 'Paschim Puri', :city_id => 2},
{:location_name => 'Paschim Vihar', :city_id => 2},
{:location_name => 'Patel Nagar', :city_id => 2},
{:location_name => 'Patiala House', :city_id => 2},
{:location_name => 'Peera Garhi', :city_id => 2},
{:location_name => 'Pitampura', :city_id => 2},
{:location_name => 'Pragati Maidan', :city_id => 2},
{:location_name => 'Prashant Vihar', :city_id => 2},
{:location_name => 'Pratap Nagar', :city_id => 2},
{:location_name => 'Preet Vihar', :city_id => 2},
{:location_name => 'Prem Nagar', :city_id => 2},
{:location_name => 'Priyadarshini Vihar', :city_id => 2},
{:location_name => 'Pulpehladpur', :city_id => 2},
{:location_name => 'Punjabi Bagh', :city_id => 2},
{:location_name => 'Punjabi Bagh East', :city_id => 2},
{:location_name => 'Punjabi Bagh Extension', :city_id => 2},
{:location_name => 'Punjabi Bagh, West Punjabi Bagh', :city_id => 2},
{:location_name => 'Pusa Road', :city_id => 2},
{:location_name => 'Pushp Vihar', :city_id => 2},
{:location_name => 'Qutab Institutional Area', :city_id => 2},
{:location_name => 'R K Puram Sector 1', :city_id => 2},
{:location_name => 'R K Puram Sector 12', :city_id => 2},
{:location_name => 'R K Puram Sector 9', :city_id => 2},
{:location_name => 'Radhey Puri Extension', :city_id => 2},
{:location_name => 'Raghubir Nagar', :city_id => 2},
{:location_name => 'Railway Road', :city_id => 2},
{:location_name => 'Raj Nagar', :city_id => 2},
{:location_name => 'Raja Garden', :city_id => 2},
{:location_name => 'Rajeev Nagar', :city_id => 2},
{:location_name => 'Rajendra Nagar', :city_id => 2},
{:location_name => 'Rajendra Place', :city_id => 2},
{:location_name => 'Rajgarh Colony', :city_id => 2},
{:location_name => 'Rajouri Garden', :city_id => 2},
{:location_name => 'Ram Nagar', :city_id => 2},
{:location_name => 'Ramakrishna Puram', :city_id => 2},
{:location_name => 'Ramesh Nagar', :city_id => 2},
{:location_name => 'Rampura', :city_id => 2},
{:location_name => 'Rana Pratap Bagh', :city_id => 2},
{:location_name => 'Rangpuri', :city_id => 2},
{:location_name => 'Rani Bagh', :city_id => 2},
{:location_name => 'Rani Jhansi Road', :city_id => 2},
{:location_name => 'Ranjit Nagar', :city_id => 2},
{:location_name => 'Red Fort', :city_id => 2},
{:location_name => 'RK Puram', :city_id => 2},
{:location_name => 'RK Puram, Sector 6', :city_id => 2},
{:location_name => 'RK Puram, Sector 8', :city_id => 2},
{:location_name => 'Rohini', :city_id => 2},
{:location_name => 'Rohini, Sector 1', :city_id => 2},
{:location_name => 'Rohini, Sector 10', :city_id => 2},
{:location_name => 'Rohini, Sector 11', :city_id => 2},
{:location_name => 'Rohini, Sector 13', :city_id => 2},
{:location_name => 'Rohini, Sector 14', :city_id => 2},
{:location_name => 'Rohini, Sector 15', :city_id => 2},
{:location_name => 'Rohini, Sector 16', :city_id => 2},
{:location_name => 'Rohini, Sector 17', :city_id => 2},
{:location_name => 'Rohini, Sector 18', :city_id => 2},
{:location_name => 'Rohini, Sector 2', :city_id => 2},
{:location_name => 'Rohini, Sector 24', :city_id => 2},
{:location_name => 'Rohini, Sector 3', :city_id => 2},
{:location_name => 'Rohini, Sector 4', :city_id => 2},
{:location_name => 'Rohini, Sector 5', :city_id => 2},
{:location_name => 'Rohini, Sector 6', :city_id => 2},
{:location_name => 'Rohini, Sector 7', :city_id => 2},
{:location_name => 'Rohini, Sector 8', :city_id => 2},
{:location_name => 'Rohini, Sector 9', :city_id => 2},
{:location_name => 'Rohtak Road', :city_id => 2},
{:location_name => 'Rohtash Nagar', :city_id => 2},
{:location_name => 'Rohtash Nagar', :city_id => 2},
{:location_name => 'Roop Nagar', :city_id => 2},
{:location_name => 'Roshan Pura', :city_id => 2},
{:location_name => 'Roshanara Road', :city_id => 2},
{:location_name => 'Sadar bazaar', :city_id => 2},
{:location_name => 'Sadar Thana Road', :city_id => 2},
{:location_name => 'Sadatpur', :city_id => 2},
{:location_name => 'Safdarjanj Enclave', :city_id => 2},
{:location_name => 'Safdarjung Development Area', :city_id => 2},
{:location_name => 'Safdarjung Enclave', :city_id => 2},
{:location_name => 'Sagarpur', :city_id => 2},
{:location_name => 'Saini Enclave', :city_id => 2},
{:location_name => 'Sainik Farm', :city_id => 2},
{:location_name => 'Saiyad Ul Ajaib', :city_id => 2},
{:location_name => 'Saket', :city_id => 2},
{:location_name => 'Samaipur Libaspur Road', :city_id => 2},
{:location_name => 'Samay Pur', :city_id => 2},
{:location_name => 'Sangam Vihar', :city_id => 2},
{:location_name => 'Sanjay Colony', :city_id => 2},
{:location_name => 'Sanjay Gandhi Transport Nagar', :city_id => 2},
{:location_name => 'Sansad Marg', :city_id => 2},
{:location_name => 'Sant Nagar', :city_id => 2},
{:location_name => 'Sarai Jullena', :city_id => 2},
{:location_name => 'Sarai Rohilla', :city_id => 2},
{:location_name => 'Saraswati Vihar', :city_id => 2},
{:location_name => 'Sardar Bazar', :city_id => 2},
{:location_name => 'Sarita Vihar', :city_id => 2},
{:location_name => 'Sarojini Nagar', :city_id => 2},
{:location_name => 'Sarojini Nagar Market', :city_id => 2},
{:location_name => 'Sarvapriya Vihar', :city_id => 2},
{:location_name => 'Sarvodaya Enclave', :city_id => 2},
{:location_name => 'Satya Niketan', :city_id => 2},
{:location_name => 'Savita Vihar', :city_id => 2},
{:location_name => 'Savitri Nagar', :city_id => 2},
{:location_name => 'Sector 1, Noida', :city_id => 2},
{:location_name => 'Sector 10, Noida', :city_id => 2},
{:location_name => 'Sector 11, Ghaziabad', :city_id => 2},
{:location_name => 'Sector 11, Noida', :city_id => 2},
{:location_name => 'Sector 12, Ghaziabad', :city_id => 2},
{:location_name => 'Sector 12, IMT Manesar', :city_id => 2},
{:location_name => 'Sector 12, Noida', :city_id => 2},
{:location_name => 'Sector 14, Gurgaon', :city_id => 2},
{:location_name => 'Sector 15, Gurgaon', :city_id => 2},
{:location_name => 'Sector 15, Noida', :city_id => 2},
{:location_name => 'Sector 15A, Faridaba', :city_id => 2},
{:location_name => 'Sector 16, Faridabad', :city_id => 2},
{:location_name => 'Sector 16, Noida', :city_id => 2},
{:location_name => 'Sector 18, Noida', :city_id => 2},
{:location_name => 'Sector 19, Noida', :city_id => 2},
{:location_name => 'Sector 2, Noida', :city_id => 2},
{:location_name => 'Sector 22, Noida', :city_id => 2},
{:location_name => 'Sector 26, Noida', :city_id => 2},
{:location_name => 'Sector 27, Noida', :city_id => 2},
{:location_name => 'Sector 29, Noida', :city_id => 2},
{:location_name => 'Sector 3, Ghaziabad', :city_id => 2},
{:location_name => 'Sector 31, Noida', :city_id => 2},
{:location_name => 'Sector 37, Noida', :city_id => 2},
{:location_name => 'Sector 38, Noida', :city_id => 2},
{:location_name => 'Sector 38A, Noida', :city_id => 2},
{:location_name => 'Sector 4, Ghaziabad', :city_id => 2},
{:location_name => 'Sector 41, Noida', :city_id => 2},
{:location_name => 'Sector 44, Noida', :city_id => 2},
{:location_name => 'Sector 49, Noida', :city_id => 2},
{:location_name => 'Sector 5, Noida', :city_id => 2},
{:location_name => 'Sector 50, Noida', :city_id => 2},
{:location_name => 'Sector 51, Noida', :city_id => 2},
{:location_name => 'Sector 53 Gurgaon', :city_id => 2},
{:location_name => 'Sector 53, Noida', :city_id => 2},
{:location_name => 'Sector 57, Noida', :city_id => 2},
{:location_name => 'Sector 6, Noida', :city_id => 2},
{:location_name => 'Sector 61, Noida', :city_id => 2},
{:location_name => 'Sector 62, Noida', :city_id => 2},
{:location_name => 'Sector 63, Noida', :city_id => 2},
{:location_name => 'Sector 7, Faridabad', :city_id => 2},
{:location_name => 'Sector 9, Ghazia', :city_id => 2},
{:location_name => 'Sector 9, Noida', :city_id => 2},
{:location_name => 'Seelampur', :city_id => 2},
{:location_name => 'Seemapuri', :city_id => 2},
{:location_name => 'Sewa Nagar', :city_id => 2},
{:location_name => 'Shadipur', :city_id => 2},
{:location_name => 'Shahdara', :city_id => 2},
{:location_name => 'Shahpur Jat', :city_id => 2},
{:location_name => 'Shakarpur', :city_id => 2},
{:location_name => 'Shakarpur Extension', :city_id => 2},
{:location_name => 'Shakarpur Khas', :city_id => 2},
{:location_name => 'Shakti Nagar', :city_id => 2},
{:location_name => 'Shakur Basti', :city_id => 2},
{:location_name => 'Shakurpur', :city_id => 2},
{:location_name => 'Shakurpur Colony', :city_id => 2},
{:location_name => 'Shalimar Bagh', :city_id => 2},
{:location_name => 'Shalimar Park', :city_id => 2},
{:location_name => 'Shankar Nagar', :city_id => 2},
{:location_name => 'Shanti Niketan', :city_id => 2},
{:location_name => 'Sharda Puri', :city_id => 2},
{:location_name => 'Shastri Nagar', :city_id => 2},
{:location_name => 'Shastri Park', :city_id => 2},
{:location_name => 'Sheikh Sarai', :city_id => 2},
{:location_name => 'Sheikh Sarai Phase-2', :city_id => 2},
{:location_name => 'Shiv Nagar', :city_id => 2},
{:location_name => 'Shiv Puri', :city_id => 2},
{:location_name => 'Shivalik', :city_id => 2},
{:location_name => 'Shivpuri', :city_id => 2},
{:location_name => 'Shraddhanand Marg', :city_id => 2},
{:location_name => 'Shreshtha Vihar', :city_id => 2},
{:location_name => 'Silampur', :city_id => 2},
{:location_name => 'Simapuri Old', :city_id => 2},
{:location_name => 'Siri Fort Road', :city_id => 2},
{:location_name => 'Sirkiwalan', :city_id => 2},
{:location_name => 'Sitaram Bazar', :city_id => 2},
{:location_name => 'South Extension Part 1 ', :city_id => 2},
{:location_name => 'South Extension Part II', :city_id => 2},
{:location_name => 'South Patel Nagar', :city_id => 2},
{:location_name => 'Srinivaspuri', :city_id => 2},
{:location_name => 'Subhash Nagar', :city_id => 2},
{:location_name => 'Sukhdev Vihar', :city_id => 2},
{:location_name => 'Sultanpuri', :city_id => 2},
{:location_name => 'Sundar Nagar', :city_id => 2},
{:location_name => 'Sunder Vihar', :city_id => 2},
{:location_name => 'Supreme Court', :city_id => 2},
{:location_name => 'Surajmal Vihar', :city_id => 2},
{:location_name => 'Surya Nagar', :city_id => 2},
{:location_name => 'Swasthya Vihar', :city_id => 2},
{:location_name => 'Tagore Garden Extension', :city_id => 2},
{:location_name => 'Taimoor Nagar', :city_id => 2},
{:location_name => 'Tank Road', :city_id => 2},
{:location_name => 'Tigri', :city_id => 2},
{:location_name => 'Tilak Marg', :city_id => 2},
{:location_name => 'Tilak nagar', :city_id => 2},
{:location_name => 'Timarpur', :city_id => 2},
{:location_name => 'Tis hazari', :city_id => 2},
{:location_name => 'Tis hazari Court', :city_id => 2},
{:location_name => 'Tolstoy Marg', :city_id => 2},
{:location_name => 'Trilokpuri', :city_id => 2},
{:location_name => 'Tughlaqabad', :city_id => 2},
{:location_name => 'Tughlaqabad Extension', :city_id => 2},
{:location_name => 'Turkman Gate', :city_id => 2},
{:location_name => 'Uday Park', :city_id => 2},
{:location_name => 'Udyog Nagar', :city_id => 2},
{:location_name => 'Uttam Nagar', :city_id => 2},
{:location_name => 'Vasant Enclave', :city_id => 2},
{:location_name => 'Vasant Kunj, Sector-A', :city_id => 2},
{:location_name => 'Vasant Kunj, Sector-B', :city_id => 2},
{:location_name => 'Vasant Kunj, Sector-c', :city_id => 2},
{:location_name => 'Vasant Kunj, Sector-D', :city_id => 2},
{:location_name => 'Vasant Vihar', :city_id => 2},
{:location_name => 'Vashisht Park', :city_id => 2},
{:location_name => 'Vasundhara Enclave', :city_id => 2},
{:location_name => 'Vigyan Vihar', :city_id => 2},
{:location_name => 'Vijay Enclave', :city_id => 2},
{:location_name => 'Vijay Nagar', :city_id => 2},
{:location_name => 'Vikas Marg', :city_id => 2},
{:location_name => 'Vikaspuri', :city_id => 2},
{:location_name => 'Vinod Nagar West', :city_id => 2},
{:location_name => 'Vishnu Garden', :city_id => 2},
{:location_name => 'Vishwas Nagar', :city_id => 2},
{:location_name => 'Vivek Vihar', :city_id => 2},
{:location_name => 'Wazir Nagar', :city_id => 2},
{:location_name => 'Wazirabad', :city_id => 2},
{:location_name => 'Wazirpur', :city_id => 2},
{:location_name => 'Wazirpur Industrial Area', :city_id => 2},
{:location_name => 'Wazirpur Village', :city_id => 2},
{:location_name => 'West Patel Nagar', :city_id => 2},
{:location_name => 'West Sagarpur', :city_id => 2},
{:location_name => 'Yamuna Vihar', :city_id => 2},
{:location_name => 'Yojana Vihar', :city_id => 2},
{:location_name => 'Yusuf Sarai', :city_id => 2},
{:location_name => 'Zakir Nagar', :city_id => 2}, 
{:location_name => 'Zamrudpur', :city_id => 2},

{:location_name => 'Ballabhgarh', :city_id => 3},
{:location_name => 'Garima Garden', :city_id => 3},
{:location_name => 'Greenfield Colony', :city_id => 3},
{:location_name => 'Gurgaon Road', :city_id => 3},
{:location_name => 'Jawahar Colony', :city_id => 3},
{:location_name => 'Jeevan Nagar', :city_id => 3},
{:location_name => 'Mujesar', :city_id => 3},
{:location_name => 'New Industrial TownShip', :city_id => 3},
{:location_name => 'New Industrial Township 1', :city_id => 3},
{:location_name => 'NIT Faridabad', :city_id => 3},
{:location_name => 'Old Faridabad', :city_id => 3},
{:location_name => 'Rajeev Nagar', :city_id => 3},
{:location_name => 'Ram Nagar', :city_id => 3},
{:location_name => 'Sanjay Colony', :city_id => 3},
{:location_name => 'Sanjay Gandhi Memorial Nagar', :city_id => 3},
{:location_name => 'Sector 15A, Faridabad', :city_id => 3},
{:location_name => 'Sector 16, Faridabad', :city_id => 3},
{:location_name => 'Sector 7, Faridabad', :city_id => 3},

{:location_name => 'Ambedkar Road', :city_id => 4},
{:location_name => 'Ashok Nagar', :city_id => 4},
{:location_name => 'Bhim Nagar', :city_id => 4},
{:location_name => 'Bhopura', :city_id => 4},
{:location_name => 'Brij Vihar', :city_id => 4},
{:location_name => 'Bulandshahr Road Industrial Area', :city_id => 4},
{:location_name => 'chikamberpur', :city_id => 4},
{:location_name => 'Chiranjeev Vihar', :city_id => 4},
{:location_name => 'Dasna Gate', :city_id => 4},
{:location_name => 'Gandhi Nagar', :city_id => 4},
{:location_name => 'Garima Garden', :city_id => 4},
{:location_name => 'Hapur Road', :city_id => 4},
{:location_name => 'Indirapuram', :city_id => 4},
{:location_name => 'Indrapuri', :city_id => 4},
{:location_name => 'Jatwara', :city_id => 4},
{:location_name => 'Jawahar Nagar', :city_id => 4},
{:location_name => 'Kailash Nagar', :city_id => 4},
{:location_name => 'Kallupura', :city_id => 4},
{:location_name => 'Kamala Nagar', :city_id => 4},
{:location_name => 'Kaushambi', :city_id => 4},
{:location_name => 'Kavi Nagar', :city_id => 4},
{:location_name => 'Kavi Nagar Industrial Area', :city_id => 4},
{:location_name => 'Lal Kuan', :city_id => 4},
{:location_name => 'Lohia Nagar', :city_id => 4},
{:location_name => 'Loni', :city_id => 4},
{:location_name => 'Maliwara', :city_id => 4},
{:location_name => 'Meerut Road', :city_id => 4},
{:location_name => 'Meerut Road Industrial Area', :city_id => 4},
{:location_name => 'Mohan Nagar', :city_id => 4},
{:location_name => 'Nehru Nagar', :city_id => 4},
{:location_name => 'Panchsheel Park', :city_id => 4},
{:location_name => 'Pandav Nagar', :city_id => 4},
{:location_name => 'Patel Nagar', :city_id => 4},
{:location_name => 'Railway Road', :city_id => 4},
{:location_name => 'Raj Nagar', :city_id => 4},
{:location_name => 'Rajendra Nagar', :city_id => 4},
{:location_name => 'Ram Nagar', :city_id => 4},
{:location_name => 'Ramteram Road', :city_id => 4},
{:location_name => 'Sahibabad', :city_id => 4},
{:location_name => 'Sahibabad Industrial Area', :city_id => 4},
{:location_name => 'Sahibabad Industrial Area Site 4', :city_id => 4},
{:location_name => 'Sangam Vihar', :city_id => 4},
{:location_name => 'Sanjay Colony', :city_id => 4},
{:location_name => 'Sector 11, Ghaziabad', :city_id => 4},
{:location_name => 'Sector 12, Ghaziabad', :city_id => 4},
{:location_name => 'Sector 3, Ghaziabad', :city_id => 4},
{:location_name => 'Sector 4, Ghaziabad', :city_id => 4},
{:location_name => 'Sector 9, Ghaziabad', :city_id => 4},
{:location_name => 'Sewa Nagar', :city_id => 4},
{:location_name => 'Shalimar Garden', :city_id => 4},
{:location_name => 'Shalimar Garden Extention 1', :city_id => 4},
{:location_name => 'Shalimar Garden Extention 2', :city_id => 4},
{:location_name => 'Shastri Nagar', :city_id => 4},
{:location_name => 'Shivpuri', :city_id => 4},
{:location_name => 'Surya Nagar', :city_id => 4},
{:location_name => 'Turab Nagar', :city_id => 4},
{:location_name => 'Vaishali, Sector 1', :city_id => 4},
{:location_name => 'Vaishali, Sector 2', :city_id => 4},
{:location_name => 'Vaishali, Sector 3', :city_id => 4},
{:location_name => 'Vaishali, Sector 4', :city_id => 4},
{:location_name => 'Vaishali, Sector 5', :city_id => 4},
{:location_name => 'Vasundhara', :city_id => 4},
{:location_name => 'Vijay Nagar', :city_id => 4},

{:location_name => 'Basai', :city_id => 5},
{:location_name => 'Basai Road', :city_id => 5},
{:location_name => 'Bhim Nagar', :city_id => 5},
{:location_name => 'Chakkarpur Market', :city_id => 5},
{:location_name => 'Dayanand Colony', :city_id => 5},
{:location_name => 'Delhi Road', :city_id => 5},
{:location_name => 'DLF City Phase - II', :city_id => 5},
{:location_name => 'DLF City Phase - III', :city_id => 5},
{:location_name => 'DLF City Phase - IV', :city_id => 5},
{:location_name => 'DLF City Phase 1', :city_id => 5},
{:location_name => 'DLF Industrial Area', :city_id => 5},
{:location_name => 'Gandhi Nagar', :city_id => 5},
{:location_name => 'Hasanpur', :city_id => 5},
{:location_name => 'IMT Manesar', :city_id => 5},
{:location_name => 'Islampur', :city_id => 5},
{:location_name => 'Jacombpura', :city_id => 5},
{:location_name => 'Jail Road', :city_id => 5},
{:location_name => 'Jawahar Nagar', :city_id => 5},
{:location_name => 'Khandsa Road', :city_id => 5},
{:location_name => 'Manesar', :city_id => 5},
{:location_name => 'Mehrauli Gurgaon Road', :city_id => 5},
{:location_name => 'Mehrauli Road', :city_id => 5},
{:location_name => 'New Colony', :city_id => 5},
{:location_name => 'New Railway Road', :city_id => 5},
{:location_name => 'NH 8', :city_id => 5},
{:location_name => 'Old DLF Colony', :city_id => 5},
{:location_name => 'Palam Vihar', :city_id => 5},
{:location_name => 'Palam Vihar Road', :city_id => 5},
{:location_name => 'Patel Nagar', :city_id => 5},
{:location_name => 'Pratap Nagar', :city_id => 5},
{:location_name => 'Prem Nagar', :city_id => 5},
{:location_name => 'Railway Road', :city_id => 5},
{:location_name => 'Rajeev Nagar', :city_id => 5},
{:location_name => 'Rajiv Nagar', :city_id => 5},
{:location_name => 'Ram Nagar', :city_id => 5},
{:location_name => 'Roshan Pura', :city_id => 5},
{:location_name => 'Saraswati Vihar', :city_id => 5},
{:location_name => 'Sector 14, Gurgaon', :city_id => 5},
{:location_name => 'Sector 15, Gurgaon', :city_id => 5},
{:location_name => 'Sector 53 Gurgaon', :city_id => 5},
{:location_name => 'Shakti Nagar', :city_id => 5},
{:location_name => 'Shivpuri', :city_id => 5},
{:location_name => 'Sikandarpur', :city_id => 5},
{:location_name => 'Sohna Road', :city_id => 5},
{:location_name => 'South City I', :city_id => 5},
{:location_name => 'Subhash Nagar', :city_id => 5},
{:location_name => 'Sukhrali', :city_id => 5},
{:location_name => 'Sultanpur', :city_id => 5},
{:location_name => 'Sushant Lok', :city_id => 5},
{:location_name => 'Sushant Lok I', :city_id => 5},
{:location_name => 'Sushant Lok II', :city_id => 5},
{:location_name => 'Udyog Vihar', :city_id => 5},
{:location_name => 'Udyog Vihar Phase 2', :city_id => 5},
{:location_name => 'Udyog Vihar Phase III', :city_id => 5},
{:location_name => 'Udyog Vihar Phase IV', :city_id => 5},
{:location_name => 'Udyog Vihar Phase V', :city_id => 5},
{:location_name => 'Vishnu Garden', :city_id => 5},
{:location_name => 'Wazirabad', :city_id => 5},

{:location_name => 'Ashok Nagar', :city_id => 6},
{:location_name => 'Atta Market', :city_id => 6},
{:location_name => 'Bhangel', :city_id => 6},
{:location_name => 'Dadri Road', :city_id => 6},
{:location_name => 'Gautam Budh Nagar', :city_id => 6},
{:location_name => 'Greater Noida', :city_id => 6},
{:location_name => 'Harola', :city_id => 6},
{:location_name => 'Khora Colony', :city_id => 6},
{:location_name => 'Mamura', :city_id => 6},
{:location_name => 'New Ashok Nagar', :city_id => 6},
{:location_name => 'Phase 2, Noida', :city_id => 6},
{:location_name => 'Sangam Vihar', :city_id => 6},
{:location_name => 'Sector 1, Noida', :city_id => 6},
{:location_name => 'Sector 10, Noida', :city_id => 6},
{:location_name => 'Sector 11, Noida', :city_id => 6},
{:location_name => 'Sector 12, Noida', :city_id => 6},
{:location_name => 'Sector 15, Noida', :city_id => 6},
{:location_name => 'Sector 16, Noida', :city_id => 6},
{:location_name => 'Sector 18, Noida', :city_id => 6},
{:location_name => 'Sector 19, Noida', :city_id => 6},
{:location_name => 'Sector 2, Noida', :city_id => 6},
{:location_name => 'Sector 22, Noida', :city_id => 6},
{:location_name => 'Sector 26, Noida', :city_id => 6},
{:location_name => 'Sector 27, Noida', :city_id => 6},
{:location_name => 'Sector 29, Noida', :city_id => 6},
{:location_name => 'Sector 31, Noida', :city_id => 6},
{:location_name => 'Sector 37, Noida', :city_id => 6},
{:location_name => 'Sector 38, Noida', :city_id => 6},
{:location_name => 'Sector 38A, Noida', :city_id => 6},
{:location_name => 'Sector 41, Noida', :city_id => 6},
{:location_name => 'Sector 44, Noida', :city_id => 6},
{:location_name => 'Sector 49, Noida', :city_id => 6},
{:location_name => 'Sector 5, Noida', :city_id => 6},
{:location_name => 'Sector 50, Noida', :city_id => 6},
{:location_name => 'Sector 51, Noida', :city_id => 6},
{:location_name => 'Sector 53, Noida', :city_id => 6},
{:location_name => 'Sector 57, Noida', :city_id => 6},
{:location_name => 'Sector 6, Noida', :city_id => 6},
{:location_name => 'Sector 61, Noida', :city_id => 6},
{:location_name => 'Sector 62, Noida', :city_id => 6},
{:location_name => 'Sector 63, Noida', :city_id => 6},
{:location_name => 'Sector 9, Noida', :city_id => 6}
])